name: generalCheck
run-name: Runs lint check and tests on push
on: 
    push:
        branches:
            - main

jobs:
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install depts
              run: npm ci
            - name: Lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install depts
              run: npm ci
            - name: Test
              run: echo Hello world!; npm test