name: generalCheck
run-name: Runs lint check and tests on push
on: 
    push:
        branches:
            - main

jobs:
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'

            - name: Install depts
              run: npm ci

            - name: Lint
              run: npm run lint
    test:
        needs: [lint-check]
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node: [ 16, 18, 20 ]
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node }}

            - name: Install depts
              run: npm ci

            - name: Build and Test
              run: | 
                echo Hello ${{ secrets.SECRET_TOKEN}}!
                npm run build --if-present
                npm test

    test-with-coverage:
      needs: [lint-check]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4

          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 20

          - name: Install depts
            run: npm ci

          - name: Build and Test
            run: npm run test:cov

          - name: Upload test coverage report
            uses: actions/upload-artifact@v3
            with:
              name: app-coverage
              path: ./coverage/